"""T057 — every aggregate is reproduced by summing the outcomes (SC-004, EVA-17c).

This is the test that catches a denominator edit that looked right.

The hazard is specific. Denominators are the part a contributor reaches for when
a number looks unflattering, and every plausible edit -- excluding unevaluated
documents, dropping unlabelled fields from the total, counting absence labels in
the coverage base -- produces a report that is internally consistent, plausible,
and wrong. No single number looks odd. The only thing that breaks is the identity
between the outcomes and the aggregates, and nothing checks that by eye.

So Hypothesis generates datasets and prediction sets, and this asserts:

1. **Every reported aggregate equals a tally of the per-field outcomes.** No
   number is reachable only by trusting the reporter.
2. **``coverage + missing_rate + unevaluated_rate == 1``** over the value labels,
   exactly. Every value label resolves to exactly one of answered / blank / not
   run, so the three rates partition |V| -- and any denominator edit breaks the
   sum before it breaks anything a human would notice.
"""

from __future__ import annotations

from decimal import Decimal

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from docdoc.evaluation import (
    DocumentPrediction,
    EvaluationError,
    Expectation,
    GoldenDocument,
    GoldenSet,
    Label,
    PredictionSet,
    Tier,
    evaluate,
)
from docdoc.evaluation.metrics import count_outcomes
from docdoc.evaluation.score import value_path_index
from docdoc.evaluation.tiers import DocumentOrigin, OriginKind
from tests.fixtures.evaluation.datasets import INVOICE, registry
from tests.support import make_extracted, make_extraction

#: Scalar invoice fields, so generated labels always resolve. Deliberately not
#: generated: an invented field path would test the loader, not the arithmetic.
FIELDS = ("invoice_number", "currency", "total", "supplier.legal_name", "supplier.tax_id")

_SCHEMA_HASH = registry().resolve(INVOICE).schema_hash

_ORIGIN = DocumentOrigin(
    kind=OriginKind.SYNTHETIC,
    basis="Generated by Hypothesis for the reconciliation property.",
    generator_id="tests.property.test_metrics_reconcile",
    generator_version="1.0.0",
)


def _document(index: int, labels: int) -> GoldenDocument:
    return GoldenDocument(
        document_id=f"doc-{index}",
        blob_sha256="sha256:" + f"{index:064d}",
        tier=Tier.PUBLIC,
        origin=_ORIGIN,
        schema_identity=INVOICE,
        schema_hash=_SCHEMA_HASH,
        path=f"documents/doc-{index}.txt",
        declared_label_count=labels,
    )


#: One field's fate: what the truth says, and what the run produced.
#: ``absent`` means the label asserts a correct absence.
_FATES = st.sampled_from(["correct", "incorrect", "missing", "absent_ok", "spurious"])


@st.composite
def _dataset(draw: st.DrawFn) -> tuple[GoldenSet, PredictionSet]:
    """A golden set and a prediction set, with each document's fate drawn.

    Three document-level shapes are generated as well as field-level ones,
    because the aggregates differ across them: a document may process normally,
    fail part-way, or have no prediction at all.
    """
    count = draw(st.integers(min_value=1, max_value=6))
    documents: list[GoldenDocument] = []
    labels: dict[str, tuple[Label, ...]] = {}
    predictions: dict[str, DocumentPrediction] = {}

    for index in range(count):
        chosen = draw(st.lists(_FATES, min_size=1, max_size=len(FIELDS), unique_by=lambda _: None))
        fates = dict(zip(FIELDS, chosen, strict=False))
        shape = draw(st.sampled_from(["ok", "failed", "absent"]))

        document_labels: list[Label] = []
        values: dict[str, object] = {}

        for field, fate in fates.items():
            if fate == "correct":
                document_labels.append(
                    Label(field_path=field, expectation=Expectation.VALUE, value=_value(field))
                )
                values[field] = make_extracted(field, value=_value(field), present=True)
            elif fate == "incorrect":
                document_labels.append(
                    Label(field_path=field, expectation=Expectation.VALUE, value=_value(field))
                )
                values[field] = make_extracted(field, value=_other(field), present=True)
            elif fate == "missing":
                document_labels.append(
                    Label(field_path=field, expectation=Expectation.VALUE, value=_value(field))
                )
                values[field] = make_extracted(field, value=None, present=False)
            elif fate == "absent_ok":
                document_labels.append(Label(field_path=field, expectation=Expectation.ABSENT))
                values[field] = make_extracted(field, value=None, present=False)
            else:
                document_labels.append(Label(field_path=field, expectation=Expectation.ABSENT))
                values[field] = make_extracted(field, value=_value(field), present=True)

        documents.append(_document(index, len(document_labels)))
        labels[f"doc-{index}"] = tuple(document_labels)

        if shape == "absent":
            continue

        nested: dict[str, object] = {}
        for path, extracted in values.items():
            if "." in path:
                group, leaf = path.split(".", 1)
                nested.setdefault(group, {})[leaf] = extracted  # type: ignore[index]
            else:
                nested[path] = extracted

        predictions[f"doc-{index}"] = DocumentPrediction(
            document_id=f"doc-{index}",
            extraction=make_extraction(nested, schema_identity=INVOICE, schema_hash=_SCHEMA_HASH),
            failed_stage=None if shape == "ok" else "ground",  # type: ignore[arg-type]
            failure_reason=None if shape == "ok" else "GroundingError",
            parser_id="test_parser",
            parser_version="1.0.0",
        )

    return (
        GoldenSet(documents=tuple(documents), labels=labels),
        PredictionSet(predictions=predictions, recorder_id="hypothesis", recorder_version="1.0.0"),
    )


def _value(field: str) -> object:
    return Decimal("10.00") if field == "total" else f"{field}-value"


def _other(field: str) -> object:
    return Decimal("11.00") if field == "total" else f"{field}-other"


@settings(max_examples=200, deadline=None)
@given(_dataset())
def test_summing_the_outcomes_reproduces_every_aggregate(
    pair: tuple[GoldenSet, PredictionSet],
) -> None:
    """FR-055: no aggregate is reachable only by trusting the reporter."""
    golden, predictions = pair
    report = evaluate(golden, predictions)
    counts = report.metrics.counts

    tallies = {
        "correct": 0,
        "incorrect": 0,
        "missing": 0,
        "spurious": 0,
        "unlabeled": 0,
        "unevaluated": 0,
    }
    for outcome in report.outcomes:
        tallies[str(outcome.kind)] += 1

    assert counts.correct == tallies["correct"]
    assert counts.incorrect == tallies["incorrect"]
    assert counts.missing == tallies["missing"]
    assert counts.spurious == tallies["spurious"]
    assert counts.unlabeled == tallies["unlabeled"]
    assert counts.unevaluated == tallies["unevaluated"]

    assert counts.labelled == sum(v for k, v in tallies.items() if k != "unlabeled")


@settings(max_examples=200, deadline=None)
@given(_dataset())
def test_the_metrics_divide_the_counts_they_report(
    pair: tuple[GoldenSet, PredictionSet],
) -> None:
    """Every metric's own numerator and denominator agree with its value (FR-029)."""
    golden, predictions = pair
    report = evaluate(golden, predictions)

    for name, metric in report.metrics.micro.items():
        if metric.denominator == 0:
            assert metric.value is None, name
        else:
            assert metric.value == metric.numerator / metric.denominator, name


@settings(max_examples=200, deadline=None)
@given(_dataset())
def test_coverage_missing_and_unevaluated_partition_the_value_labels(
    pair: tuple[GoldenSet, PredictionSet],
) -> None:
    """EVA-17c: the three rates sum to exactly 1 over |V|.

    Every value label resolves to exactly one of *answered* (right or wrong),
    *blank*, or *never run*. Compared as integers rather than floats, because a
    float sum of three exact rationals is not exactly 1 and the requirement is
    about the partition, not about IEEE 754.
    """
    golden, predictions = pair
    report = evaluate(golden, predictions)

    coverage = report.metrics.micro["coverage"]
    missing = report.metrics.micro["missing_rate"]
    unevaluated_rate = report.metrics.micro["unevaluated_rate"]
    counts = report.metrics.counts

    if counts.value_labels == 0:
        assert coverage.value is None
        assert missing.value is None
        return

    assert coverage.denominator == missing.denominator == counts.value_labels
    assert coverage.numerator + missing.numerator + counts.unevaluated_value == (
        counts.value_labels
    ), (
        "the three fates of a value label do not partition |V|; a denominator has "
        "been edited or an outcome is being counted in two partitions"
    )

    # And the unevaluated rate divides the whole labelled surface, not |V| --
    # stated because the two coincide whenever a dataset has no absence labels,
    # which is most of them.
    assert unevaluated_rate.denominator == counts.labelled


@settings(max_examples=200, deadline=None)
@given(_dataset())
def test_the_document_scores_sum_to_the_dataset_counts(
    pair: tuple[GoldenSet, PredictionSet],
) -> None:
    """One document, one contribution. Nothing double-counted, nothing dropped."""
    golden, predictions = pair
    report = evaluate(golden, predictions)

    for field in ("correct_value", "incorrect", "missing", "spurious", "unlabeled"):
        summed = sum(getattr(score.counts, field) for score in report.document_scores)
        assert summed == getattr(report.metrics.counts, field), field


@settings(max_examples=100, deadline=None)
@given(_dataset())
def test_every_labelled_field_receives_exactly_one_outcome(
    pair: tuple[GoldenSet, PredictionSet],
) -> None:
    """The closed set is a partition, not a menu.

    Two outcomes for one label would inflate a numerator and a denominator
    together, which is nearly invisible in the resulting rate.
    """
    golden, predictions = pair
    report = evaluate(golden, predictions)

    labelled = {
        (document_id, label.field_path)
        for document_id, labels in golden.labels.items()
        for label in labels
    }
    reported = [
        (o.document_id, o.field_path) for o in report.outcomes if str(o.kind) != "unlabeled"
    ]

    assert sorted(reported) == sorted(labelled)
    assert len(reported) == len(set(reported))


# -- the runtime invariant (T097, FR-055) ------------------------------------
#
# The property tests above check the datasets Hypothesis happens to generate.
# `dataset_metrics` checks every report anyone produces, which is the difference
# between an invariant that holds in the suite and one that holds in the product.


def test_the_reconciliation_runs_on_every_report() -> None:
    """It is not opt-in, and it is not only in the tests."""
    from docdoc.evaluation.metrics import _reconcile

    golden, predictions = _fixed_dataset()
    report = evaluate(golden, predictions)

    # The same check the scorer just ran, re-run by hand over the report it
    # produced: if this diverged, the aggregate a reader sees would not be the
    # one the outcomes support.
    _reconcile(
        report.metrics.counts,
        [score.counts for score in report.document_scores],
        [
            count_outcomes(
                [o for o in report.outcomes if o.field_path == path],
                value_paths=value_path_index(golden),
            )
            for path in sorted({o.field_path for o in report.outcomes})
        ],
    )


def test_a_lost_outcome_is_refused_rather_than_reported() -> None:
    """The failure mode, forced.

    A per-document view missing one outcome is what a filtering bug looks like:
    every number is plausible, every rate is well-formed, and the dataset total
    quietly disagrees with the documents it is supposedly made of.
    """
    from docdoc.evaluation.metrics import OutcomeCounts, _reconcile

    dataset = OutcomeCounts(correct_value=10, incorrect=2)

    with pytest.raises(EvaluationError, match="do not reconcile"):
        _reconcile(dataset, [OutcomeCounts(correct_value=9, incorrect=2)], [dataset])


def test_the_refusal_names_the_tally_and_both_sides() -> None:
    """contracts §8 — a caller that has to parse prose to find the gap will not."""
    from docdoc.evaluation.metrics import OutcomeCounts, _reconcile

    dataset = OutcomeCounts(missing=5)

    with pytest.raises(EvaluationError) as raised:
        _reconcile(dataset, [OutcomeCounts(missing=3)], [dataset])

    assert raised.value.field_path == "missing"
    assert raised.value.expected == "5"
    assert raised.value.actual == "3"


def test_a_negative_tally_is_refused_at_construction() -> None:
    """The one invariant the counts model can check on its own.

    A negative tally means a subtraction reached a counter, and every metric
    dividing it is reporting a number with no interpretation.
    """
    from pydantic import ValidationError

    from docdoc.evaluation.metrics import OutcomeCounts

    with pytest.raises(ValidationError, match="must not be negative"):
        OutcomeCounts(missing=-1)


def _fixed_dataset() -> tuple[GoldenSet, PredictionSet]:
    """One small dataset, built without Hypothesis, for the non-property tests."""
    labels = (
        Label(field_path="invoice_number", expectation=Expectation.VALUE, value="INV-1"),
        Label(field_path="total", expectation=Expectation.VALUE, value=Decimal("1.00")),
        Label(field_path="supplier.tax_id", expectation=Expectation.ABSENT),
    )
    document = _document(0, len(labels))
    values = {
        "invoice_number": make_extracted("invoice_number", value="INV-1", present=True),
        "total": make_extracted("total", value=Decimal("2.00"), present=True),
        "supplier": {"tax_id": make_extracted("supplier.tax_id", present=False)},
    }
    return (
        GoldenSet(documents=(document,), labels={"doc-0": labels}),
        PredictionSet(
            predictions={
                "doc-0": DocumentPrediction(
                    document_id="doc-0",
                    extraction=make_extraction(
                        values, schema_identity=INVOICE, schema_hash=_SCHEMA_HASH
                    ),
                    parser_id="test",
                    parser_version="1.0.0",
                )
            },
            recorder_id="fixed",
            recorder_version="1.0.0",
        ),
    )
