"""T014 — a document whose provenance cannot be stated is not admitted (FR-011).

FR-011 is not a formality, and this file exists because it reads like one. Two
distinct failures hide behind the same wording:

**An empty ``basis``.** The basis is the answer to "on what grounds may docdoc
use this document". "Found on the internet" is not one. A repository that
vendors documents without that answer is one licence complaint away from having
to delete its dataset -- and with it every number ever computed from it.

**A synthetic document that does not name its generator.** It cannot be
regenerated, so nobody can check the labels against the thing that produced the
document those labels describe. The labels become unverifiable, which makes them
assertions, which is the exact category of claim Principle IX exists to replace.

Both are enforced in ``DocumentOrigin``'s validators, so they fire whether a
document is constructed in Python or read from a manifest -- and both paths are
checked here, because a rule that holds on one of them is a rule with a way
around it.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
from pydantic import ValidationError

from docdoc.evaluation import EvaluationError, load_golden_set
from docdoc.evaluation.tiers import DocumentOrigin, OriginKind
from tests.fixtures.evaluation.authoring_errors import (
    origin_with_empty_basis,
    synthetic_without_generator,
    write_dataset,
)
from tests.fixtures.evaluation.datasets import facts_for_fixtures

if TYPE_CHECKING:
    from pathlib import Path


# -- constructed in Python ---------------------------------------------------


@pytest.mark.parametrize("basis", ["", "   ", "\n\t "])
def test_a_document_without_a_stated_basis_is_not_admitted(basis: str) -> None:
    """Whitespace is not a basis. Somebody typed a space to make a check pass."""
    with pytest.raises(ValidationError, match="basis"):
        DocumentOrigin(kind=OriginKind.PUBLIC_DOMAIN, basis=basis)


def test_a_stated_basis_is_admitted() -> None:
    """The guard on the guard: the check must discriminate, not just refuse."""
    origin = DocumentOrigin(
        kind=OriginKind.PUBLIC_DOMAIN,
        basis="Published by the issuing authority under an open licence.",
    )

    assert origin.basis


@pytest.mark.parametrize(
    ("generator_id", "generator_version"),
    [(None, None), ("gen", None), (None, "1.0.0")],
)
def test_a_synthetic_document_must_name_its_generator(
    generator_id: str | None, generator_version: str | None
) -> None:
    """Both halves, and either one alone is not enough.

    An id without a version names a program that has since changed; a version
    without an id names nothing at all. Regenerating the document requires both,
    and regenerating it is what makes its labels checkable.
    """
    with pytest.raises(ValidationError, match="generator"):
        DocumentOrigin(
            kind=OriginKind.SYNTHETIC,
            basis="Synthetic.",
            generator_id=generator_id,
            generator_version=generator_version,
        )


def test_a_non_synthetic_document_needs_no_generator() -> None:
    """The requirement is scoped to the kind that has one.

    A licensed document was not generated by a program, so demanding a generator
    would push authors to write a placeholder -- and a placeholder in a
    provenance field is worse than an absent one, because it reads as an answer.
    """
    origin = DocumentOrigin(
        kind=OriginKind.LICENSED,
        basis="Licensed for evaluation use under the supplier agreement.",
    )

    assert origin.generator_id is None


# -- read from a manifest ----------------------------------------------------


def test_an_empty_basis_is_refused_at_load(tmp_path: Path) -> None:
    """The path a maintainer actually takes, and it must refuse the same way."""
    manifest = write_dataset(tmp_path, origin_with_empty_basis())

    with pytest.raises(EvaluationError) as raised:
        load_golden_set(manifest, facts=facts_for_fixtures())

    assert "no-basis" in str(raised.value)
    assert raised.value.document_id == "no-basis"


def test_a_generatorless_synthetic_document_is_refused_at_load(tmp_path: Path) -> None:
    manifest = write_dataset(tmp_path, synthetic_without_generator())

    with pytest.raises(EvaluationError) as raised:
        load_golden_set(manifest, facts=facts_for_fixtures())

    assert "no-generator" in str(raised.value)
    assert raised.value.document_id == "no-generator"


def test_the_manifest_refusal_is_an_evaluation_error_not_a_validation_error(
    tmp_path: Path,
) -> None:
    """The type is part of the contract (contracts §8).

    A raw pydantic ``ValidationError`` escaping the loader would make a dataset
    authoring mistake indistinguishable from a bug in docdoc, and would carry no
    ``document_id`` for the caller to search on.
    """
    manifest = write_dataset(tmp_path, origin_with_empty_basis())

    with pytest.raises(EvaluationError):
        load_golden_set(manifest, facts=facts_for_fixtures())
